### ISSUE TITLE
Invalid arguement supplied to foreach calling ratedGoodByOther($id)

### ISSUE THREAD

**Issue by michaeljhopkins** [AntoineAugusti/laravel-easyrec#3]
attempting to execute the command `Easyrec::ratedGoodByOther(4)`, where 4 is a valid id of an item that I have supplied a number of ratings for, returns the following. `ErrorException in Easyrec.php line 447: Invalid argument supplied for foreach()`

And to see a bit more of the stacktrack
http://i.imgur.com/eJDbCYn.png

**Comment by AntoineAugusti** [comment]
Hey,

Can you var_dump what you have in the result array when you are making the call? I'm really interested about the `recommendeditems`.

**Comment by michaeljhopkins** [comment]
it doesn't get that far. That error is thrown when attempting to do 

![](http://i.imgur.com/g1DuTQm.png)

**Comment by AntoineAugusti** [comment]
Yep, that's normal. Can you temporarly var_dump the `$result` variable in the private function `sendRequest` of the Easyrec class, in your vendor directory? I bet that the key `recommendeditems` key is present but it's not an array.

**Comment by michaeljhopkins** [comment]
ahhhh, yeah. on it

**Comment by michaeljhopkins** [comment]
So you are right. Empty array. I'm wondering if I did a poor job seeding. Calling `Easyrec::mostRatedItems();` works, for whatever it's worth.
![](http://i.imgur.com/jgUhvRs.png)

**Comment by AntoineAugusti** [comment]
Okay, I see. I'll add a check to prevent from iterating over an empty array. Maybe it doesn't give results yet because I think that recommendations aren't run in real time, but are rather computed with a CRON task on the Easyrec side.

**Comment by michaeljhopkins** [comment]
Just checked out the faq on easyrecs' side and you're spot on. Run's once a day automatically. YOu can force an update, but not in demo. Thanks for the quick reply and help!

**Comment by AntoineAugusti** [comment]
@michael-hopkins Okay, great to have an answer. Just pushed a commit to prevent that. Will include that in the next release ;)
