### ISSUE TITLE
[Feature Request] BestRatedItems of selected subset

### ISSUE THREAD

**Issue by michaeljhopkins** [AntoineAugusti/laravel-easyrec#4]
I'm not quite sure the work that would be entailed in this. Using the MovieLens dataset, each movie is given 17 true/false fields for genres. For example, if you wanted to retrieve an array of id's for all the western movies

```
 $movieIds = Movie::whereWestern(1)->get()->lists('id');
```

This led me to look at the `Easyrec::bestRatedItems()` method to see if I could pass the about `$movieIds` to get the best rated of that subset. It would be neat if that was possible.

**Comment by AntoineAugusti** [comment]
Unfortunately I don't think that it is offered by the Easyrec API (http://easyrec.sourceforge.net/wiki/index.php?title=REST_API_v0.98#best_rated_items).

You can create a custom item type, something like `MOVIE-WESTERN` but I agree it's not the best way to go.

If you have another idea I'm totally ready to take a look!
