### ISSUE TITLE
Separate branch for Laravel 4

### ISSUE THREAD

**Issue by aaronflorey** [AntoineAugusti/laravel-easyrec#5]
I'm running your version 0.5.\* of this for Laravel 4, but there is a bug in it. I'd like to submit a fix, but your only branch is Laravel 5 only.

**Comment by AntoineAugusti** [comment]
@Mochaka You can submit a PR to the new branch: `laravel-4`

**Comment by aaronflorey** [comment]
Thanks for getting back to me so quickly :)
