### ISSUE TITLE
Facade file has wrong case

### ISSUE THREAD

**Issue by tremby** [AntoineAugusti/laravel-easyrec#7]
The facade file `LaravelEasyRec.php` should match its class name and be `LaravelEasyrec.php`, otherwise there can be problems autoloading on case sensitive filesytems.

**Comment by AntoineAugusti** [comment]
Thanks for the heads up. Shame on me for coding that on OS X! Fixed in Laravel 4 (see #9) and Laravel 5 (see #8).

Happy Easter!
